### ISSUE TITLE
Support for yaml?

### ISSUE THREAD

**Issue by jkohlin** [YECHUNAN/json-color-token#19]
Would it be possible to add support for yaml files? 
Tried to add it to the list of languages and restarted vscode but nothing...

**Comment by YECHUNAN** [comment]
I tried it on my VSCode and it seems to be working? You need to add "yaml" to the list of "Languages" instead of the list of "CSS Languages". 
![image](https://user-images.githubusercontent.com/16599672/175142193-075427c9-bfbf-44bc-a8ef-601f2e334f60.png)

For non-CSS languages, the extension is as simple as detecting color token patterns and render color preview boxes for them. If you want more advanced support, please describe the scenarios you would like it to support and we can consider adding it if they fit into the scope of this extension.

**Comment by jkohlin** [comment]
Strange, now it actually works. I did add "yaml" to the list, but nothing happened. 
Well, if it's not broken...
Cheers 🥂
