### ISSUE TITLE
Doesn't work in JSONC file types

### ISSUE THREAD

**Issue by blaylockbk** [YECHUNAN/json-color-token#2]
Thanks for making this extension. I use it often.

I found that the extension doesn't work for JSONC (json with comments) file types.

![image](https://user-images.githubusercontent.com/6249613/129118401-4b941fa6-3af7-494b-a36c-613a43685a0a.png)

![image](https://user-images.githubusercontent.com/6249613/129118434-9d406007-f8c6-4884-adab-062a3f8f235e.png)

Probably not the best place to request this, but I would love to see the color picker show in more file types (like TOML).

**Comment by YECHUNAN** [comment]
Thanks for posting the feature request!

I published a new 1.2.0 which adds a setting to allow people declare arbitrary language to apply the color token detection. jsonc is included in the default value. Theoretically it should work for any other language where color tokens are defined to match this regex: `/#[0-9a-fA-F]{6}([0-9]{2})?/g`. I didn't exclude the detection for colors in the comments. Please let me know if that significantly disrupts your use case.

![image](https://user-images.githubusercontent.com/16599672/130393968-fe03640b-b93a-4cf3-ac17-f492ff087129.png)

Unfortunately, due to my lack of knowledge, none of the css-json interaction features will work because I don't know which library to use for parsing jsonc documents.

**Comment by blaylockbk** [comment]
This is awesome! Thank you so much. I can now use this color picker in more than just JSON, but JSONC, Python, TOML, and any other document type.
![image](https://user-images.githubusercontent.com/6249613/130665961-72cb6b6a-3fb5-4d50-86dc-90db70c7a5e9.png)

**Comment by LeonardoGentile** [comment]
@YECHUNAN Awesome!
I think you should rename this extension because it might be misleading, given that now this extension is capable of bringing up the color picker not only in json but in any language! 👍 🎉

For future readers: to make this work with js and react, add this in settings:

```
"jsonColorToken.languages": [
    "json",
    "jsonc",
    "javascript",
    "javascriptreact"
  ]
```

**Comment by eunkich** [comment]
For those of you trying to enable this feature for python, identifier should be `"python"`, not `"Python"` as in @blaylockbk's example. Reload window after adding the language identifier in settings. 

You can look for the language identifier of your interest in the following link. 
https://github.com/YECHUNAN/json-color-token/issues/10#issuecomment-951273943
