### ISSUE TITLE
Max number of color tokens

### ISSUE THREAD

**Issue by JPereira-FJB** [YECHUNAN/json-color-token#22]
Regardless of the option:
"
"jsonColorToken.maxNumberOfColorTokens": 2000
"

The max tokens is always 500. Is this a bug on my side?

**Comment by YECHUNAN** [comment]
I can reproduce this and I believe it's because we have this setting "editor.colorDecoratorsLimit" whose value is set to be 500. It's a VS Code built-in setting that controls the maximum number of color decoration it should render for each document. I am pretty sure that when I implemented the setting for this extension, that setting hasn't been added to VS Code. https://github.com/microsoft/vscode/commit/911f119120141940fcfc4d7899065ae85b72770a#diff-71d62961f9e98ee074bb1ff8e57d2446b556f5439e1b0beee63e2e9ccc8e6fc0R85

Anyway, to increase the limit in your case, you should be able to achieve that by simply bumping both that VS Code setting and the setting for json-color-token extension to a large enough number.

**Comment by JPereira-FJB** [comment]
That fixed it, thank you!
Amazing work!
